---
- name: Setting up swarm masters ...
  shell: docker-machine ls | grep {{ item.name }} || docker-machine create --driver generic \
        --engine-opt "cluster-advertise {{ cluster_interface }}:2376" \
        --engine-opt "cluster-store consul://localhost:8500" \
        --generic-ssh-user {{ user }} \
        --generic-ssh-key {{ item.ssh_key_file }} \
        --generic-ip-address {{ item.ip }} \
        --swarm \
        --swarm-master \
        --swarm-discovery "consul://localhost:8500"
        {{ item.extras }} \
        {{ item.name }}
  with_items: "{{ cluster_masters }}"
  tags: [machines]

- name: Setting up swarm nodes ...
  shell: docker-machine ls | grep {{ item.name }} || docker-machine create --driver generic \
        --engine-opt "cluster-advertise {{ cluster_interface }}:2376" \
        --engine-opt "cluster-store consul://localhost:8500" \
        --generic-ssh-user {{ user }} \
        --generic-ssh-key {{ item.ssh_key_file }} \
        --generic-ip-address {{ item.ip }} \
        --swarm \
        --swarm-discovery "consul://localhost:8500"
        {{ item.extras }} \
        {{ item.name }}
  with_items: "{{ cluster_machines }}"
  tags: [machines]
