#- name: Directories are created
#  file:
#    path: "{{ item }}"
#    state: directory
#  with_items: directories
#  tags: [consul]
#
#- name: Files are copied
#  copy:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    mode: "{{ item.mode }}"
#  with_items: files
#  tags: [consul]
#
#- name: Is running
#  shell: "nohup consul agent {{ consul_extra }} \
#    -ui-dir /data/consul/ui \
#    -data-dir /data/consul/data \
#    -config-dir /data/consul/config \
#    -node={{ ansible_hostname }} \
#    -bind={{ ip }} \
#    -client=0.0.0.0 \
#    >{{ logs_dir }}/consul.log 2>&1 &"
#  tags: [consul]
#
#- name: Has joined
#  shell: consul join {{ consul_server_ip }}
#  when: consul_server_ip is defined
#  tags: [consul]

- name: Container is running
  docker:
    image: progrium/consul
    name: consul
    hostname: "{{ ansible_hostname }}"
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8500:8500
    command: -advertise {{ facter_ipaddress_eth1 }} {{ consul_extra }}
