logs_dir: /data/consul/logs

directories:
  - /data/consul/data
  - /data/consul/config
  - "{{ logs_dir }}"

files: [
  { src: 'consul.json', dest: '/data/consul/config/consul.json', mode: '0755' },
]
